## Gaussian Elimination

In [1]:
import numpy as np

In [6]:
def gaussian(A, b):
    A = A.astype(float)
    b = b.astype(float)

    n = len(b)
    for k in range(n):
        max_row = np.argmax(abs(A[k, k:])) + k
        A[[k, max_row]] = A[[max_row, k]]
        b[[k, max_row]] = b[[max_row, k]]

        for i in range(k+1, n):
            factor = A[i][k]/A[k][k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

        x = np.zeros(n)
        for i in range(n-1, -1, -1):
            x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:]))/A[i][i]

    return x

## Gauss Siddle

In [38]:
def gauss_siddle(A, b, x0, tol = 1e-6, max_iter = 100):
    x = x0.copy()
    n = len(b)
    for iterations in range(max_iter):
        xnew = x.copy()
        for i in range(n):
            sigma = np.dot(A[i, :i], xnew[:i]) + np.dot(A[i, i+1:], x[i+1:])
            xnew[i] = (b[i] - sigma)/A[i][i]
        if np.linalg.norm(xnew - x) < tol:
            return xnew
        x = xnew
    return x

In [39]:
A = np.array([[2, 1], [3, 5]], dtype = float)
b = np.array([5, 13], dtype = float)
x0 = np.zeros(len(b), dtype = float)
x1 = gaussian(A, b)
x2 = gauss_siddle(A, b, x0)
x3 = np.linalg.solve(A , b)
x1, x2, x3

(array([1.71428571, 1.57142857]),
 array([1.71428584, 1.5714285 ]),
 array([1.71428571, 1.57142857]))

## Finding determinant from Gaussian elimination

In [2]:
def determinant(A):
    A = A.astype(float)
    
    n = len(A)
    for k in range(n):
        max_row = np.argmax(abs(A[k, k:])) + k
        A[[k, max_row]] = A[[max_row, k]]
        for i in range(k+1, n):
            factor = A[i][k]/A[k][k]
            A[i, k:] -= factor * A[k, k:]
    print(f"Transformed Matrix: {A}")
    det = np.prod(np.diag(A))
    print(f"Determinant from Gaussian Elimination: {det}")
    print(f"Determinant from linalg module: {np.linalg.det(A)}")

In [47]:
A = np.array([[2, 1], [3, 5]], dtype = float)
determinant(A)

Transformed Matrix: [[2.  1. ]
 [0.  3.5]]
Determinant from Gaussian Elimination: 7.0
Determinant from linalg module: 7.000000000000001
